import './global.css'

import type { Metadata } from 'next'
import { Cherry_Bomb_One } from 'next/font/google'

import { ProviderTheme } from '@/lib/providers/ProviderTheme'
import Web3ProviderSolana from '@/lib/providers/Web3ProvidersSolana'

import { Footer } from './components/Footer'
import { Header } from './components/Header'

const cherry = Cherry_Bomb_One({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-cherry'
})

export const metadata: Metadata = {
  title: 'Woodies',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${cherry.variable} text-text-main`}>
        <Web3ProviderSolana>
          <ProviderTheme>
            <Header />
            {children}
            <Footer />
          </ProviderTheme>
        </Web3ProviderSolana>
      </body>
    </html>
  )
}
