import './style/global.css'

import type { Metadata } from 'next'

import Web3ProviderSolana from '@/lib/providers/Web3ProvidersSolana'

// import { Footer } from './components/Footer'
import { Header } from './components/Header'

export const metadata: Metadata = {
  title: 'Woodies',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="text-white">
        <Web3ProviderSolana>
          <Header />
          {children}
          {/* <Footer /> */}
        </Web3ProviderSolana>
      </body>
    </html>
  )
}
