import './style/global.css'

import type { Metadata } from 'next'
import { Cherry_Bomb_One, Montserrat, Nunito } from 'next/font/google'

import { Footer } from './components/footer'
import { Header } from './components/header'

export const metadata: Metadata = {
  title: 'Woodies',
  description: 'Generated by create next app'
}

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['800'],
  display: 'swap',
  style: 'normal',
  variable: '--font-montserrat'
})

const nunito = Nunito({
  weight: ['400', '500'],
  subsets: ['latin'],
  style: 'normal',
  variable: '--font-nunito'
})

const cherry = Cherry_Bomb_One({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
  style: 'normal',
  variable: '--font-cherry'
})

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`text-primary ${nunito.className} ${nunito.variable} ${montserrat.variable} ${cherry.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
